import "@styles/globals.css";
import type { AppProps } from "next/app";
import { useEffect, useState, useContext, createContext } from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import "@rainbow-me/rainbowkit/styles.css";
import {
  getDefaultWallets,
  RainbowKitProvider,
  Theme,
  darkTheme,
  Chain,
} from "@rainbow-me/rainbowkit";
import { publicProvider } from "wagmi/providers/public";
import { configureChains, createClient, WagmiConfig } from "wagmi";
import merge from "lodash.merge";
import { goerli } from "wagmi/chains";
import Head from "next/head";
import Navbar from "@components/Navbar";

const thetaTestnet: Chain = {
  id: 365,
  name: "Theta Testnet",
  network: "TFUEL",
  nativeCurrency: {
    decimals: 18,
    name: "TFUEL",
    symbol: "TFUEL",
  },
  rpcUrls: {
    default: "https://eth-rpc-api-testnet.thetatoken.org/rpc",
  },
  blockExplorers: {
    default: { name: "Explorer", url: "https://beta-explorer.thetatoken.org/" },
  },
  testnet: true,
};

const { chains, provider } = configureChains(
  [thetaTestnet, goerli],
  [publicProvider()]
);

const { connectors } = getDefaultWallets({
  appName: "Tixo",
  chains,
});

const wagmiClient = createClient({
  autoConnect: true,
  connectors,
  provider,
});

const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Montserrat",
        color: "white",
      },
      a: {
        _hover: {
          textDecoration: "underline",
        },
      },
    },
  },
});

const customTheme = merge(darkTheme(), {
  colors: {
    accentColor: "#1E1E1E",
  },
} as Theme);

export const ImageContext = createContext(null);

function MyApp({ Component, pageProps, router }: AppProps) {
  const [selectedImage, setSelectedImage] = useState("/0.jpg");

  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <WagmiConfig client={wagmiClient}>
      <RainbowKitProvider chains={chains} theme={customTheme}>
        <ChakraProvider theme={theme}>
          <ImageContext.Provider value={{ selectedImage, setSelectedImage }}>
            <Head>
              <title>TIXO: NFT Ticketing</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div
              className="dynamic-bg"
              style={{
                backgroundImage: `url(${selectedImage})`,
              }}
            >
              <Component {...pageProps} key={router.route} />
            </div>
          </ImageContext.Provider>
        </ChakraProvider>
      </RainbowKitProvider>
    </WagmiConfig>
  );
}

export default MyApp;
